import { LanguageOption } from '../types';

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    speechCode: 'te-IN',
    ttsCode: 'te-IN',
  },
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    speechCode: 'en-US',
    ttsCode: 'en-US',
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    speechCode: 'hi-IN',
    ttsCode: 'hi-IN',
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    speechCode: 'ta-IN',
    ttsCode: 'ta-IN',
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    speechCode: 'kn-IN',
    ttsCode: 'kn-IN',
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    speechCode: 'ml-IN',
    ttsCode: 'ml-IN',
  },
  {
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    speechCode: 'es-ES',
    ttsCode: 'es-ES',
  },
  {
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    speechCode: 'fr-FR',
    ttsCode: 'fr-FR',
  },
];

export const DEFAULT_LANGUAGE = 'te'; // Telugu as specified by user

// Rapid dictionary translation mappings for ultra-low latency live subtitles
export const COMMON_PHRASE_DICTIONARY: Record<string, Record<string, string>> = {
  'hello': {
    te: 'నమస్కారం (Namaskaram)',
    en: 'Hello',
    hi: 'नमस्ते (Namaste)',
    ta: 'வணக்கம் (Vanakkam)',
    kn: 'ನಮಸ್ಕಾರ (Namaskara)',
    es: 'Hola',
    fr: 'Bonjour',
  },
  'hi': {
    te: 'హాయ్ / నమస్తే (Hi / Namaste)',
    en: 'Hi',
    hi: 'नमस्ते (Namaste)',
    ta: 'வணக்கம் (Vanakkam)',
    kn: 'ಹಲೋ (Halo)',
    es: 'Hola',
    fr: 'Salut',
  },
  'how are you': {
    te: 'మీరు ఎలా ఉన్నారు? (Meeru ela unnaru?)',
    en: 'How are you?',
    hi: 'आप कैसे हैं? (Aap kaise hain?)',
    ta: 'நீங்கள் எப்படி இருக்கிறீர்கள்?',
    kn: 'ನೀವು ಹೇಗಿದ್ದೀರಿ?',
    es: '¿Cómo estás?',
    fr: 'Comment allez-vous?',
  },
  'how are you doing': {
    te: 'మీరు ఎలా ఉన్నారు? (Meeru ela unnaru?)',
    en: 'How are you doing?',
    hi: 'आप कैसे हैं?',
    ta: 'எப்படி இருக்கிறீர்கள்?',
    kn: 'ಹೇಗಿದ್ದೀರಿ?',
    es: '¿Cómo te va?',
    fr: 'Comment ça va?',
  },
  'i am fine': {
    te: 'నేను బాగున్నాను (Nenu bagunnanu)',
    en: 'I am fine',
    hi: 'मैं ठीक हूँ (Main theek hoon)',
    ta: 'நான் நலமாக இருக்கிறேன்',
    kn: 'ನಾನು ಚೆನ್ನಾಗಿದ್ದೇನೆ',
    es: 'Estoy bien',
    fr: 'Je vais bien',
  },
  'can you hear me': {
    te: 'నా మాట మీకు వినపడుతోందా? (Naa maata meeku vinapaduthonda?)',
    en: 'Can you hear me?',
    hi: 'क्या आप मुझे सुन सकते हैं? (Kya aap mujhe sun sakte hain?)',
    ta: 'நான் பேசுவது கேட்கிறதா?',
    kn: 'ನನ್ನ ಧ್ವನಿ ಕೇಳಿಸುತ್ತಿದೆಯೇ?',
    es: '¿Puedes oírme?',
    fr: 'Pouvez-vous m’entendre?',
  },
  'yes i can hear you': {
    te: 'అవును, మీ మాట స్పష్టంగా వినిపిస్తోంది (Avunu, mee maata vinipisthondi)',
    en: 'Yes, I can hear you clearly',
    hi: 'हाँ, मैं आपको सुन सकता हूँ',
    ta: 'ஆம், தெளிவாக கேட்கிறது',
    kn: 'ಹೌದು, ನನಗೆ ಕೇಳಿಸುತ್ತಿದೆ',
    es: 'Sí, te escucho claramente',
    fr: 'Oui, je vous entends clairement',
  },
  'thank you': {
    te: 'ధన్యవాదాలు (Dhanyavadalu)',
    en: 'Thank you',
    hi: 'धन्यवाद (Dhanyavaad)',
    ta: 'நன்றி (Nandri)',
    kn: 'ಧನ್ಯವಾದಗಳು (Dhanyavadagalu)',
    es: 'Gracias',
    fr: 'Merci',
  },
  'welcome': {
    te: 'స్వాగతం (Swagatham)',
    en: 'Welcome',
    hi: 'स्वागत हे (Swagat hai)',
    ta: 'வரவேற்பு (Varaverpu)',
    kn: 'ಸ್ವಾಗತ (Swagatha)',
    es: 'Bienvenido',
    fr: 'Bienvenue',
  },
  'good morning': {
    te: 'శుభోదయం (Shubhodayam)',
    en: 'Good morning',
    hi: 'शुभ प्रभात (Shubh Prabhat)',
    ta: 'காலை வணக்கம் (Kaalai Vanakkam)',
    kn: 'ಶುಭೋದಯ (Shubhodaya)',
    es: 'Buenos días',
    fr: 'Bonjour',
  },
  'good evening': {
    te: 'శుభ సాయంత్రం (Shubha Sayanthram)',
    en: 'Good evening',
    hi: 'शुभ संध्या (Shubh Sandhya)',
    ta: 'மாலை வணக்கம் (Maalai Vanakkam)',
    kn: 'ಶುಭ ಸಂಜೆ (Shubha Sanje)',
    es: 'Buenas tardes',
    fr: 'Bonsoir',
  },
  'goodbye': {
    te: 'వీడ్కోలు / మళ్ళీ కలుద్దాం (Veedkolu / Mallee kaluddam)',
    en: 'Goodbye',
    hi: 'अलविदा (Alvida)',
    ta: 'பிரியாவிடை (Piriyavidai)',
    kn: 'ಬರುತ್ತೇನೆ (Baruthene)',
    es: 'Adiós',
    fr: 'Au revoir',
  },
  'see you later': {
    te: 'మళ్ళీ కలుద్దాం (Mallee kaluddam)',
    en: 'See you later',
    hi: 'फिर मिलेंगे (Phir milenge)',
    ta: 'மீண்டும் சந்திப்போம்',
    kn: 'ಮತ್ತೆ ಸಿಗೋಣ',
    es: 'Hasta luego',
    fr: 'À plus tard',
  },
  'what is your name': {
    te: 'మీ పేరు ఏమిటి? (Mee peru emiti?)',
    en: 'What is your name?',
    hi: 'आपका नाम क्या है? (Aapka naam kya hai?)',
    ta: 'உங்கள் பெயர் என்ன?',
    kn: 'ನಿಮ್ಮ ಹೆಸರು ಏನು?',
    es: '¿Cómo te llamas?',
    fr: 'Comment vous vous appelez?',
  },
  'my name is': {
    te: 'నా పేరు (Naa peru)',
    en: 'My name is',
    hi: 'मेरा नाम है (Mera naam hai)',
    ta: 'என் பெயர்',
    kn: 'ನನ್ನ ಹೆಸರು',
    es: 'Mi nombre es',
    fr: 'Mon nom est',
  },
  'nice to meet you': {
    te: 'మిమ్మల్ని కలవడం సంతోషంగా ఉంది (Mimmalni kalavadam santhoshamga undi)',
    en: 'Nice to meet you',
    hi: 'आपसे मिलकर अच्छा लगा',
    ta: 'உங்களை சந்தித்ததில் மகிழ்ச்சி',
    kn: 'ನಿಮ್ಮನ್ನು ಭೇಟಿಯಾಗಿದ್ದು ಸಂತೋಷವಾಯಿತು',
    es: 'Mucho gusto en conocerte',
    fr: 'Enchanté de vous rencontrer',
  },
  'lets start the meeting': {
    te: 'సమావేశాన్ని ప్రారంభిద్దాం (Samaveshanni prarambhiddam)',
    en: 'Let us start the meeting',
    hi: 'बैठक शुरू करते हैं',
    ta: 'கூட்டத்தை தொடங்குவோம்',
    kn: 'ಸಭೆಯನ್ನು ಪ್ರಾರಂಭಿಸೋಣ',
    es: 'Comencemos la reunión',
    fr: 'Commençons la réunion',
  },
  'please share your screen': {
    te: 'దయచేసి మీ స్క్రీన్‌ను భాగస్వామ్యం చేయండి (Dayachesi mee screen nu share cheyandi)',
    en: 'Please share your screen',
    hi: 'कृपया अपनी स्क्रीन साझा करें',
    ta: 'தயவுசெய்து உங்கள் திரையைப் பகிரவும்',
    kn: 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪರದೆಯನ್ನು ಹಂಚಿಕೊಳ್ಳಿ',
    es: 'Por favor comparte tu pantalla',
    fr: 'Veuillez partager votre écran',
  }
};
